### ISSUE TITLE
Question about loss

### ISSUE THREAD

**Issue by supertan0204** [kingnobro/AniClipart#1]
Hi,

Thanks for releasing your codes for this amazing work!

A simple question here: I realized that when running your codes, the losses remains high even after 500 iterations for every clipart optimization process. How do you know that your model eventually converged after optimization?

**Comment by kingnobro** [comment]
Yes, the SDS loss remains high even after 500 iterations, so it’s important to check the animation result to determine if it has reached convergence. Empirically, 1000 steps are enough. Currently, no algorithm automatically verifies whether the animation meets human preferences.
