### ISSUE TITLE
'-DPYTHON_LIBRARY=' + get_config_var('LIBDIR'),  TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by SmallThings-coder** [kingnobro/AniClipart#2]
Keep getting this error when trying to run` python setup.py install`

It is normal  that `get_config_var('LIBDIR')` returns None on Windows. But is it possible to run AniClipart on Windows in this case? What should I do?

**Comment by kingnobro** [comment]
I run all the code on Ubuntu. I recommend using Linux, as I may not be able to assist with errors that occur on Windows.
